Logical flow
arfc/osier pull request #71
Opened 2024-12-23 18:43 UTC by samgdotson

## Summary of changes

This PR adds a new dispatch model to `osier` called `LogicDispatchModel` that follows a hierarchy of rules to dispatch energy. It is much faster (~4x speedup) than the original `DispatchModel` but it is myopic and therefore results may be sub-optimal. Other benefits include:
- No solver required, commercial or otherwise. Thus `osier` is more self-contained.
- Easier to understand since the mathematics have been reduced to a sequence of comparisons.
- Drop-in replacement for `DispatchModel`. No change to syntax.
- Enables parallelization of the genetic algorithm driving the `CapacityExpansion` model.

>[!NOTE]
> There are a couple of new tests for new functionality. These tests should exceed the minimum code coverage required by the `pyproject.toml` file (75%). More tests are desired, but not necessary, here.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Checklist for Reviewers

Reviewers should use [this link](https://arfc.github.io/manual/guides/pull_requests) to get to the
Review Checklist before they begin their review.

2024-12-23 18:44 UTC, pep8speaks commented
Hello @samgdotson! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`osier/models/capacity_expansion.py`](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py):

> [Line 16:24](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L16): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 17:19](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L17): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 17:33](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L17): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 18:19](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L18): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 18:28](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L18): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 19:19](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L19): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 19:31](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/capacity_expansion.py#L19): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'

* In the file [`osier/models/dispatch.py`](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/dispatch.py):

> [Line 111:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/dispatch.py#L111): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

* In the file [`osier/models/logic_dispatch.py`](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py):

> [Line 14:23](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L14): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 15:34](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L15): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 21:58](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L21): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 31:23](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L31): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 43:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 45:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L45): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 46:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 47:42](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L47): [E272](https://duckduckgo.com/?q=pep8%20E272) multiple spaces before keyword
> [Line 47:51](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L47): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 47:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 48:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L48): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 54:41](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L54): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 54:42](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L54): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 54:68](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L54): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 55:41](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L55): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 72:50](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L72): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 77:47](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L77): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 79:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 81:1](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L81): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 87:80](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L87): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 90:15](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/logic_dispatch.py#L90): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`osier/models/model.py`](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py):

> [Line 47:45](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L47): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 67:37](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L67): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 68:37](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L68): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 69:37](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L69): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 76:25](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L76): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 80:42](https://github.com/arfc/osier/blob/de99762570398e282a87e0acd17b8c9f025d0b35/osier/models/model.py#L [...]

2025-01-14 16:18 UTC, LukeSeifert reviewed
Looks good! I just had a couple comments on some docstrings and the `MWh` usage. I also had some trouble running the tests myself. The tests fail with installation method 1 (from source) and method 2 for me after I cloned your [repo](https://github.com/samgdotson/osier/tree/logical_flow) and switched to the `logical_flow` branch. Do you know what I need to do to test this version of `osier`?

2025-01-14 16:18 UTC, LukeSeifert commented on osier/models/logic_dispatch.py
> +            [v if v <= 0 else 0 for v in self.covered_demand])
I understand using `t` for `technology`, but what is `v` here?

2025-01-14 16:18 UTC, LukeSeifert commented on osier/models/logic_dispatch.py
> +        Net demand is copied, then the technology histories are reset.
```suggestion
        Net demand is copied, then the technology histories are reset.
        This function executes the model solve with a rule-based approach.
```
The code appears to be in this order

2025-01-14 16:18 UTC, LukeSeifert commented on osier/models/logic_dispatch.py
> +class LogicDispatchModel(OsierModel):
No class doc string?

2025-01-14 16:18 UTC, LukeSeifert commented on osier/tech_library.py
> +                            initial_storage=0.0*MW*hr,
Why not use `MWh`?

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +            return False
```suggestion
        else:
            return self.variable_cost >= tech.variable_cost
```

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +            return False
```suggestion
        else:
            return self.variable_cost <= tech.variable_cost
```

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +            return False
```suggestion
        else:
            return self.variable_cost < tech.variable_cost
```

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
>              return False
```suggestion
        else:
            return self.variable_cost > tech.variable_cost
```

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +            to avoid ambiguity.
Missing `Returns` in docstring

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +            The difference between two timesteps. Default is one hour.
Missing `Returns` in docstring (same for next couple functions)

2025-01-14 16:18 UTC, LukeSeifert commented on osier/technology.py
> +    def discharge(self, demand: unyt_quantity, time_delta=1 * hr):
These functions are missing docstrings

2025-01-14 16:18 UTC, LukeSeifert commented on tests/test_technology.py
>  energy_unyt = 10.0 * MW * hr
You import `MWh`, consider using here

2025-01-14 16:18 UTC, LukeSeifert commented on tests/test_technology.py
> +    assert advanced_tech.om_cost_variable.units == (MW * hr)**-1
Consider using `MWh`

2025-01-14 16:18 UTC, LukeSeifert commented on tests/test_technology.py
> +    expected_unit = megatonnes * (MW * hr)**-1
Consider using MWh

2025-01-14 16:42 UTC, yardasol requested changes
Hi @samgdotson, great work on this PR. A couple items

- Docpages have not been updated to hold the new classes
- Line-items (see comments)

Additionally, it's not clear to me where the no-solver change is, nor where parallelization of the genetic algorithm is enabled. If you could describe these changes in a bit more detail that'd be wonderful!

2025-01-14 16:42 UTC, yardasol commented on osier/models/capacity_expansion.py
> +                   'rule_based': LogicDispatchModel}
`lp` feels a bit too brief. Consider making it more descriptive. And why are there 3 keys for selecting `LogicDispatchModel`? Consider condensing those into one key.

2025-01-14 16:42 UTC, yardasol commented on osier/models/logic_dispatch.py
> +class LogicDispatchModel(OsierModel):
Docstring?

2025-01-14 16:42 UTC, yardasol commented on osier/models/model.py
> +class OsierModel():
This class has a lot of shared code with `DispatchModel`. Will `DispatchModel` be refactored to inherit from `OsierModel`?

2025-01-14 16:42 UTC, yardasol commented on osier/tech_library.py
> +                            initial_storage=0.0*MW*hr,
Should this be `MWh` to reflect the shift from `MW*hr` to `MWh`?

2025-01-14 16:42 UTC, yardasol commented on osier/technology.py
> +        """Tests greater or equal to."""
```suggestion
        """Tests less or equal to."""
```

2025-01-14 16:42 UTC, yardasol commented on osier/technology.py
> +        """Tests greater or equal to."""
```suggestion
        """Tests less to."""
```

2025-01-14 16:42 UTC, yardasol commented on osier/technology.py
> +        """Tests greater or equal to."""
```suggestion
        """Tests greater to."""
```

2025-01-14 16:42 UTC, yardasol commented on osier/utils.py
> +    dispatchable_techs : list of :class:`osier.Technology`
Good name change

2025-01-14 16:42 UTC, yardasol commented on osier/utils.py
> +    storage_techs : list of :class:`osier.Technology`
```suggestion
    nonstorage_techs : list of :class:`osier.Technology`
```

2025-01-14 16:42 UTC, yardasol commented on osier/technology.py
> +    def discharge(self, demand: unyt_quantity, time_delta=1 * hr):
Docstring?

2025-01-14 16:42 UTC, yardasol commented on osier/technology.py
> +    def charge(self, surplus, time_delta=1 * hr):
Docstring?

2025-01-14 18:13 UTC, samgdotson commented on osier/technology.py
> +            return False
Could you elaborate on this?

2025-01-14 18:55 UTC, samgdotson reviewed
Thanks for the reviews @yardasol and @LukeSeifert!

2025-01-14 18:55 UTC, samgdotson commented on osier/models/logic_dispatch.py
> +            [v if v <= 0 else 0 for v in self.covered_demand])
v is for voltage.

2025-01-14 18:55 UTC, samgdotson commented on osier/models/model.py
> +class OsierModel():
Yes, that is the dream. I realized there was going to be significant overlap in these two classes but not enough overlap to warrant directly inheriting from `DispatchModel`.

2025-01-14 19:17 UTC, samgdotson commented
@yardasol, just addressing your comments/questions:

1. There is no parallelization algorithm in this PR. The PR _enables_ parallelization. 
2. The "no-solver" change lives in `CapacityExpansion` where I added a flag called `model_engine`.

The docs should be updated, now. Also, I'm not sure why the GH actions are failing, but it's not anything related to the code.

2025-01-14 21:08 UTC, LukeSeifert approved these changes
Looks good! I made a comment on one docstring that has the parameters missing, everything else seems good to me

2025-01-14 21:08 UTC, LukeSeifert commented on osier/technology.py
> +        Calculates the power output given a demand value.
Missing parameters

2025-01-14 22:07 UTC, samgdotson commented
@LukeSeifert @yardasol if you're satisfied with the changes feel free to merge (in spite of the failing checks -- I think it is a GH issue).

2025-01-15 14:51 UTC, samgdotson commented
Okay, I think the issue is because Mambaforge is no longer being maintained, so the installer is looking for a link that doesn't go anywhere, anymore. See this [release](https://github.com/conda-forge/miniforge/releases/tag/24.11.2-0).

Working on a fix.

2025-01-15 15:15 UTC, samgdotson commented
@yardasol, checks pass, now. Are you satisfied with the changes?

@LukeSeifert, regarding testing locally, I can't say for sure what's wrong because I haven't seen the error message. However, I speculate that the errors might be because you haven't "installed" the branch. Try creating an editable installation (as described in the [contributing guide](https://osier.readthedocs.io/en/latest/contrib.html)) with 

```bash
python -m pip install -e .[doc]
```

This way, you can switch between branches at will and the "installed version" of `osier` will follow code changes (including changing branches).

2025-01-15 17:49 UTC, yardasol approved these changes
Good changed @samgdotson. I found one little snag but other than that we're good to go!

2025-01-15 17:49 UTC, yardasol commented on osier/models/capacity_expansion.py
> +        Default is 'optimal'.
Good description.

2025-01-15 17:49 UTC, yardasol commented on osier/models/capacity_expansion.py
> +                   }
Good!

2025-01-15 17:49 UTC, yardasol commented on osier/technology.py
> +            The maximum achievable power level.
```suggestion
        min_power : :class:`unyt.unyt_quantity`
            The minimum achievable power level.
```

2025-01-15 20:26 UTC, samgdotson commented
Thanks @yardasol! Feel free to merge whenever!

2025-01-15 20:37 UTC, merged